// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfAXzHkC3xJ7HSjYHMa7igx8zgsWw4V7o',
    appId: '1:878460818622:web:0c1e9fe94cb8a15e843aef',
    messagingSenderId: '878460818622',
    projectId: 'achilleservice-287e7',
    authDomain: 'achilleservice-287e7.firebaseapp.com',
    storageBucket: 'achilleservice-287e7.appspot.com',
    measurementId: 'G-72BSYW369V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZnM1jFaqhobv5_AepUMcPEfmf2h-Xb2Y',
    appId: '1:878460818622:android:0e4bf746e1510d9e843aef',
    messagingSenderId: '878460818622',
    projectId: 'achilleservice-287e7',
    storageBucket: 'achilleservice-287e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiMgH8lublChb9QLbDTzTjPrm8Y0GPqys',
    appId: '1:878460818622:ios:9d06e2618c796706843aef',
    messagingSenderId: '878460818622',
    projectId: 'achilleservice-287e7',
    storageBucket: 'achilleservice-287e7.appspot.com',
    iosClientId: '878460818622-f55mif260q549cqjvu0f36b4ibm0v0ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.achilleservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiMgH8lublChb9QLbDTzTjPrm8Y0GPqys',
    appId: '1:878460818622:ios:9d06e2618c796706843aef',
    messagingSenderId: '878460818622',
    projectId: 'achilleservice-287e7',
    storageBucket: 'achilleservice-287e7.appspot.com',
    iosClientId: '878460818622-f55mif260q549cqjvu0f36b4ibm0v0ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.achilleservice',
  );
}
